use_frameworks!

platform :ios, '11.0'
source 'https://github.com/Wangyixuan/WYXPodsSpec.git'

target 'WYXPbNetwork_Example' do
  pod 'WYXPbNetwork', :path => '../'

  target 'WYXPbNetwork_Tests' do
    inherit! :search_paths

    
  end
end
